/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminMetadataRouteImport } from './routes/admin.metadata'
import { Route as AdminMembershipsRouteImport } from './routes/admin.memberships'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMembersIdRouteImport } from './routes/admin.members.$id'

const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetadataRoute = AdminMetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembershipsRoute = AdminMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersIdRoute = AdminMembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminMembersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/membership': typeof MembershipRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/metadata': typeof AdminMetadataRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/membership': typeof MembershipRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/metadata': typeof AdminMetadataRoute
  '/admin': typeof AdminIndexRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/membership': typeof MembershipRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/metadata': typeof AdminMetadataRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/booking'
    | '/contact'
    | '/courses'
    | '/membership'
    | '/admin/login'
    | '/admin/members'
    | '/admin/memberships'
    | '/admin/metadata'
    | '/admin/'
    | '/admin/members/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/courses'
    | '/membership'
    | '/admin/login'
    | '/admin/members'
    | '/admin/memberships'
    | '/admin/metadata'
    | '/admin'
    | '/admin/members/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/booking'
    | '/contact'
    | '/courses'
    | '/membership'
    | '/admin/login'
    | '/admin/members'
    | '/admin/memberships'
    | '/admin/metadata'
    | '/admin/'
    | '/admin/members/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  MembershipRoute: typeof MembershipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metadata': {
      id: '/admin/metadata'
      path: '/metadata'
      fullPath: '/admin/metadata'
      preLoaderRoute: typeof AdminMetadataRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/memberships': {
      id: '/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AdminMembershipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members/$id': {
      id: '/admin/members/$id'
      path: '/$id'
      fullPath: '/admin/members/$id'
      preLoaderRoute: typeof AdminMembersIdRouteImport
      parentRoute: typeof AdminMembersRoute
    }
  }
}

interface AdminMembersRouteChildren {
  AdminMembersIdRoute: typeof AdminMembersIdRoute
}

const AdminMembersRouteChildren: AdminMembersRouteChildren = {
  AdminMembersIdRoute: AdminMembersIdRoute,
}

const AdminMembersRouteWithChildren = AdminMembersRoute._addFileChildren(
  AdminMembersRouteChildren,
)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMembersRoute: typeof AdminMembersRouteWithChildren
  AdminMembershipsRoute: typeof AdminMembershipsRoute
  AdminMetadataRoute: typeof AdminMetadataRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminMembersRoute: AdminMembersRouteWithChildren,
  AdminMembershipsRoute: AdminMembershipsRoute,
  AdminMetadataRoute: AdminMetadataRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  MembershipRoute: MembershipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
